# YugaWare configuration
yugabyte:
    admin:
        host: localhost
        port: 9000
        user: admin
        password: admin
    service:
        name: yugabyte-db
        description: Service Broker for Managing YugaByte DB
    catalog:
        plans:
          -
            code: xsmall
            name: x-small
            cores: 2
            memory: 4
            bullets:
              - "2 CPU and 2GB Memory for the master nodes"
              - "2 CPU and 4GB Memory for the data nodes"
              - "Ideal for dev/staging environments"
            cloud_instance_type:
                aws: c4.large
                gcp: n1-standard-2
                kubernetes: xsmall
          -
            code: small
            name: small
            cores: 4
            memory: 7.5
            bullets:
              - "2 CPU and 4GB Memory for the master nodes"
              - "4 CPU and 7.5GB Memory for the data nodes"
              - "Ideal for dev/staging environments"
            cloud_instance_type:
                aws: c4.xlarge
                gcp: n1-standard-4
                kubernetes: small
          -
            code: medium
            name: medium
            cores: 8
            memory: 15
            bullets:
              - "2 CPU and 4GB Memory for the master nodes"
              - "8 CPU and 15GB Memory for the data nodes"
              - "Ideal for staging/production environments"
            cloud_instance_type:
                aws: c4.2xlarge
                gcp: n1-standard-8
                kubernetes: medium
          -
            code: large
            name: large
            cores: 16
            memory: 15
            bullets:
              - "2 CPU and 4GB Memory for the master nodes"
              - "16 CPU and 15GB Memory for the data nodes"
              - "Ideal for production environments"
            cloud_instance_type:
                aws: c4.4xlarge
                gcp: n1-standard-16
                kubernetes: large
          -
            code: xlarge
            name: x-large
            cores: 32
            memory: 30
            bullets:
              - "2 CPU and 4GB Memory for the master nodes"
              - "32 CPU and 30GB Memory for the data nodes"
              - "Ideal for production environments"
            cloud_instance_type:
                aws: c4.8xlarge
                gcp: n1-standard-32
                kubernetes: xlarge
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/yugabyte_sb
        username: yugabyte
        password: supersecret
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect

